---
title: "Envelope extraction"
author: "Šárka Kadavá"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
In this script, we extract amplitude envelope and F0

```{r folder setup}

curfolder   <- dirname(getwd())
folderstotrack <- paste0(curfolder, "/dyad0_preview/")
wav_files <- list.files(pattern = "\\.wav$", recursive = TRUE, full.names = TRUE)



```

This is a function to extract amplitude envelope
```{r setup}

library(rPraat) #for reading in sounds
library(dplR)   #for applying Hanning
library(seewave) #for signal processing general
library(wrassp) #for acoustic processing

##################### MAIN FUNCTION TO EXTRACT SMOOTHED ENVELOPE ###############################
amplitude_envelope.extract <- function(locationsound, smoothingHz, resampledHz)
{
  #read the sound file into R
  snd <- rPraat::snd.read(locationsound)
  #apply the hilbert on the signal
  hilb <- seewave::hilbert(snd$sig, f = snd$fs, fftw =FALSE)
  #apply complex modulus
  env <- as.vector(abs(hilb))
  #smooth with a hanning window
  env_smoothed <- dplR::hanning(x= env, n = snd$fs/smoothingHz)
  #set undeterminable at beginning and end NA's to 0
  env_smoothed[is.na(env_smoothed)] <- 0
  #resample settings at desired sampling rate
  f <- approxfun(1:(snd$duration*snd$fs),env_smoothed)
  #resample apply
  downsampled <- f(seq(from=0,to=snd$duration*snd$fs,by=snd$fs/resampledHz))
  #let function return the downsampled smoothed amplitude envelope
  return(downsampled[!is.na(downsampled)])
}


```

## Extract and smooth

```{r pressure, echo=FALSE}

sample <- wav_files[1]

env <- amplitude_envelope.extract(sample, 8, 2500)
acoustics <- cbind.data.frame(env)
acoustics$time_s <- seq(0, (nrow(acoustics)-1)*1/2500, 1/2500)
```

### Plot
```{r}

library(ggplot2)

exampleenvelope <- ggplot(acoustics, aes(x=time_s)) +
  geom_path(aes(y=env), size =1) 
```

### Apply for all wav. files

```{r}


# Create an empty list to store the results
result_list <- list()

# Loop over each WAV file
for (file_path in wav_files) {
    # Extract the filename without extension
    file_name <- tools::file_path_sans_ext(basename(file_path))

    # Apply your function to extract the amplitude envelope
    env <- amplitude_envelope.extract(file_path, 8, 2500)
    
    # Create a data frame with the amplitude envelope and time
    acoustics <- data.frame(env = env, time_s = seq(0, (length(env) - 1) * 1/2500, 1/2500))
    
    # Save the filename along with the data
    acoustics$filename <- file_name

    # Store the result in the list
    result_list[[file_name]] <- acoustics
}

# Combine all data frames into a single data frame
combined_data <- do.call(rbind, result_list)

# Save the combined data to a CSV file
write.csv(combined_data, "amplitude_envelope.csv", row.names = FALSE)

```


